### ISSUE TITLE
${eventName}_syntax_1_verb not matching

### ISSUE THREAD

**Issue by marcovzla** [clulab/reach#223]
Why is rule `${eventName}_syntax_1_verb` not matching in this sentence?

    E3 ubiquitin protein ubiquitinates  beta-catenin.

**Comment by myedibleenso** [comment]
For reference:
```yaml
- name: ${ eventName }_syntax_1_verb
  priority: ${ priority }
  example: "We further showed, in a combined enzymatic assay, that human deoxycytidine kinase and UMP-CMP kinase together ${ verbalTriggerLemma }d araC, dFdC, and 2',3'-dideoxycytidine to their diphosphate forms."
  label: ${ label }
  action: ${ actionFlow }
  pattern: |
    trigger = [lemma=/${ verbalTriggerLemma }/ & ${triggerPrefix} & tag=/^(V|JJ)/ & !mention=ModificationTrigger]
    cause:BioChemicalEntity? = <xcomp? (nsubj | agent | <vmod) /appos|nn|conj_(and|or|nor)|cc/{,2}
    theme:BioChemicalEntity = (dobj | xcomp) /conj_(and|or|nor)|dep|cc|nn|prep_of/{,2} (>> [word=by]){,2}
    site:Site? = dobj? /prep_(at|on)|nn|conj_(and|or|nor)|cc/{,2}
```

Template instantiation:

```yaml
  # Ubiquitination
  - import: edu/arizona/sista/reach/biogrammar/events/simple-event_template.yml
    vars:
      eventName: "Ubiquitination"
      actionFlow: "mkUbiquitination"
      label: "Ubiquitination"
      verbalTriggerLemma: "ubiquitinate"
      nominalTriggerLemma: "ubiquitination"
      triggerPrefix: "!word=/(?i)^de/"
      priority: "5"
```
