### ISSUE TITLE
A case of nasty syntax

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#49]
**Bug type**: `Rules`

**Description**: nasty syntax

```scala

import edu.arizona.sista.reach.nxml.FriesEntry
import edu.arizona.sista.reach.ReachSystem

// Initialize the REACH system
val rs = new ReachSystem

def mentionsFromText(text:String):Seq[Mention]= {
  val entry = FriesEntry("test", "1", "example", "example", isTitle = false, text)
  rs.extractFrom(entry)
}

val sentenceText = "PTEN is phosphorylated and accumulated in the nucleus in response to the Spry2 deficiency to induce p53"

val mentionText = "Beyond its cytoplasmic role in negatively regulating PI3K/AKT, PTEN is phosphorylated and accumulated in the nucleus in response to the Spry2 deficiency to induce p53-mediated growth arrest independently of its phosphatase activity."

val mentions = mentionsFromText(sentenceText)
```

**Comment by myedibleenso** [comment]
Remember that this is being matched against what you see assigned to `sentenceText`.

This is the rule template matching the `Phosphorylation` (from [`simple-event_template.yml`](https://github.com/clulab/reach/blob/72f3f8eece7125028f239830aa1c105837a13d4d/src/main/resources/edu/arizona/sista/reach/biogrammar/events/simple-event_template.yml#L24-L33)):

```yaml
- name: ${ eventName }_syntax_2_verb
  priority: 4
  label: ${ label }
  action: ${ actionFlow }
  pattern: |
    trigger = [lemma=/${ verbalTriggerLemma }/ & !word=/(?i)^de/ & tag=/^(V|JJ)/ & !mention=ModificationTrigger]
    cause:BioChemicalEntity? = (agent|prep_by) (vmod dobj)? /conj_(and|or|nor)|nn|cc|prep_of/{,2}
    theme:BioChemicalEntity = (>nsubjpass prep_of?|<vmod) /conj_(and|or|nor)|nn|cc/{,2}
    site:Site? = (agent|prep_by /conj_(and|or|nor)|nn|cc|prep_of/{,2})? /prep_(at|on)|conj_/{1,2}
```

Here is the rule template matching the `Activation` (from [`pos-reg_template.ml`](https://github.com/clulab/reach/blob/72f3f8eece7125028f239830aa1c105837a13d4d/src/main/resources/edu/arizona/sista/reach/biogrammar/events/pos-reg_template.yml#L60-L68)):

```yaml
- name: Positive_${ ruleType }_syntax_5_verb
  priority: ${ priority }
  example: ""
  label: ${ label }
  action: ${ actionFlow }
  pattern: |
    trigger = [word=/(?i)^(${ triggers })/ & tag=/^V|RB/] [lemma=/^(${ auxtriggers })/ & tag=/^V/]?
    controlled:${ controlledType } = dobj /nn|amod|conj_|cc/{,2}
    controller:${ controllerType } = (< /xcomp|rcmod|appos/){1,2} /appos|nn|amod|conj_|cc/{,2}
```

...the parse:

![nasty-1](https://cloud.githubusercontent.com/assets/1137472/12667008/9264650c-c603-11e5-8234-472bfedde597.png)


...and the result:

![nasty-1-result](https://cloud.githubusercontent.com/assets/1137472/12667014/9cc4dd06-c603-11e5-8518-b3ec202e67b1.png)
